name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.2
        with:
          github_access_token: ${{ secrets.ACCESS_TOKEN }}
          base_href: /berthout-tp2/
          deploy_branch: gh-pages
          angular_dist_build_folder: dist/simple-app
